name: Prebuild

on:
  push:
    branches:
    - main
  pull_request:
  workflow_call:

jobs:
  prebuild:
    name: Prebuild

    strategy:
      matrix:
        runs-on: [ubuntu-22.04, windows-2022, macos-15-intel]
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v7
    - name: Install pnpm
      uses: pnpm/action-setup@v6
    - name: Use Node.js 22
      uses: actions/setup-node@v7
      with:
        node-version: 22
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install

    - name: Prebuild
      run: |
        pnpm node-gyp build
        pnpm pkg-prebuilds-copy --baseDir build/Release --source tree-sitter-compat.node --name=tree-sitter-compat --strip --napi_version=8

    - name: Prebuild (arm64)
      if: startsWith(matrix.runs-on, 'macos')
      run: |
        pnpm node-gyp build --arch arm64
        pnpm pkg-prebuilds-copy --baseDir build/Release --source tree-sitter-compat.node --name=tree-sitter-compat --strip --napi_version=8 --arch arm64

    - uses: actions/upload-artifact@v7
      with:
        name: prebuilds-${{ matrix.runs-on }}
        path: prebuilds
