name: Prebuild

on:
  push:
    branches:
    - main
  pull_request:
  workflow_call:

jobs:
  prebuild:
    name: Prebuild

    strategy:
      matrix:
        runs-on: [ubuntu-22.04, windows-2022, macos-13]
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install dependencies
      run: npm ci

    - name: Prebuild
      run: npm run build:prebuild

    - name: Prebuild (arm64)
      if: startsWith(matrix.runs-on, 'macos')
      run: npm run build:prebuild -- --arch arm64

    - uses: actions/upload-artifact@v4
      with:
        name: prebuilds-${{ matrix.runs-on }}
        path: prebuilds
