name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  prebuild:
    name: Prebuild
    uses: ./.github/workflows/prebuild.yml

  publish:
    name: Publish
    runs-on: ubuntu-22.04
    needs: [prebuild]
    environment:
      name: npm
      url: https://www.npmjs.com/package/tree-sitter-compat

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Download prebuilds
        uses: actions/download-artifact@v4
        with:
          pattern: prebuilds-*
          merge-multiple: true
          path: prebuilds

      - name: Publish prebuilds
        run: pnpm prebuild --upload-all ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: pnpm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
